sudo: false

arch: amd64
os: linux
dist: bionic

language: java
jdk:
  - openjdk8

branches:
  only:
  - main
  - "/^v[0-9\\.]+(-rc[0-9]+)?/"

notifications:
  email: false

# Caching so the next build will be fast too.
cache:
  apt: true
  directories:
    - $HOME/.m2

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install --no-install-recommends -y build-essential
  - sudo apt-get install --no-install-recommends -y maven ant curl git file binutils

script:
  - ./scripts/build.sh -d `cat NEOLOGD_VERSION_DATE` -L releases/lucene-solr/`cat LUCENE_VERSION`

deploy:
  provider: releases
  api_key:
    secure: "fJ/HSpYXbNfy9Xsr/Gj1e/69Mcn4zy9AmiTzRj9YE4Ke+G4JSRWrP6+EFvEAiW7CnS2MaHocPCDpD3lBsR5eHQXKkH01ozxg6/iBrw+TiAe+ibAc8bdy12JG3JHKXG8j6SS1zqk+gpAnobCFuv5nM7y/cw5wM12yUVUZ8yWpa+C81NggsCNLM9nG1WS+xg8fo+YEGQxhErcOGTGPbVwlWGihRRHy51saUWh1x/jlXq/zQi8R7jivx31chshtjG+Ox+K6i0ZIe5rduXlMIxt5qP8hEkmsGA3ohc6LNIw9PnrvHoRyXrSK79dUlkIKOhVog58I1p150uzg8k6RqninEAeXr3GmXzKliQcH/Il/4dRVqCW0IlCp8C/fF5WuUQlnR+8H3/mT3tRzj+Jr8nuhOrwnQJQN/4Z745vPxkiW3mE3fuRcaR4de0TovsEow7aPPqDjzvAHJbdCpSa7UAttTw/fmm0BwGOb+hwjCfIc3FVpPOxiq/PVxpmXvB1CSAeEitc3mmhpJwOO1EFVM8vlW1A7KQKQSdkkx0yx3Q09zv26R6+7mhhaetk+nS8ZFcqRPYZ0uwde+1LHRrY74C0/GoabydZ0PN14N1sZPQBEleQAGRZuEUAkNM6e5zcxKd7iFR31DfLl9fVjbZq1O1+eRfnOkc+8J5LN8AsPN8u6Kcw="
  file_glob: true
  file: dist/*.jar
  on:
    repo: myui/lucene-analyzers-kuromoji-neologd
    tags: true
  skip_cleanup: true # do not delete the built assets
  overwrite: true
