sudo: false

arch: amd64
os: linux
dist: bionic

language: java
jdk:
  - openjdk8

branches:
  only:
  - main
  - "/^v[0-9\\.]+(-rc[0-9]+)?/"

notifications:
  email: false

# Caching so the next build will be fast too.
cache:
  apt: true
  directories:
    - $HOME/.m2

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install --no-install-recommends -y build-essential
  - sudo apt-get install --no-install-recommends -y maven ant curl git file binutils

script:
  - ./scripts/build.sh -d `cat NEOLOGD_VERSION_DATE` -L releases/lucene-solr/`cat LUCENE_VERSION`

deploy:
  provider: releases
  api_key:
    secure: "rSCRXsXbHDhg6u13RRXb+ZPAJPOQVK+A5XQhY3A/yLKmk04bJ/PPAwbynmZkqMezmVbK9Q2dhdsWR4o7kYIzO93A7IJDmTOs13VROaeSC2kMfHHr/pMknoZGRd8VcIfLk57xmnh1gRUVYRhUtfypCs1pMpJ+9aIZS6tXbyVelN0Kk3cpxdV5m28foTsIaz2kk1T3DieWhTFg6+L/2bcRuhUm3QPAXL7U6YZ6ACQSZfYfT6WLt5aGgNGQcPp9CIKKccWIW890iZn4azmwwERICeAwAlm/X/Yx2nzxMwJXi21Lzmm6I1QSYHWfGnoA0hGYzjFPZbW36nv/FLltJIdqps20A1H6FxJlPhYRlqutnUx/PpTb/iTFnc4MKT1yb58bcQvx6bydJUvUS2e8/icJWtxNN4GQ3qMqNO3uMj+IXoYwYaEtI0PfGjpvUhuU4FVSTZizJ3zNCA5/hiJL+LJiUSD6dgKyUNb8VKSuCfU7AT6f63vMcfSaTB+f5Ulyd5EMdUqOg/HdsVAKKb1UIWwVL0K4x74JK2SPxWznpXFyQVV8Bbi41vblI5XxnO9mQ/a7Zhx+0dZ4X7U3bK3gU06vh1leMCk1t+xcrEmxfvjxhydNau+7BNcOHAgae7bSkPzUsYtnyNhw6Gt7ni9oNVzX2ViD0UqLgA/3NnqqzzwP1YI="
  file_glob: true
  file: dist/*.jar
  on:
    repo: myui/lucene-analyzers-kuromoji-neologd
    tags: true
  skip_cleanup: true # do not delete the built assets
  overwrite: true
